<?php
/**
 * CapitalizationModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * CapitalizationModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CapitalizationModelAttributes
{
    public string $strSmallCamel = 'small_camel';
    public string $strCapitalCamel = 'capital_camel';
    public string $strSmallSnake = 'small_snake';
    public string $strCapitalSnake = 'capital_snake';
    public string $strScaEthFlowPoints = 'sca_eth_flow_points';
    public string $strAttName = 'att_name';
}

