<?php
/**
 * EnumTestModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * EnumTestModelFields Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnumTestModelFields
{
    public string $strEnumString = 'enum_string';
    public string $strEnumStringRequired = 'enum_string_required';
    public string $strEnumInteger = 'enum_integer';
    public string $strEnumNumber = 'enum_number';
    public string $strOuterEnum = 'outerEnum';
    public string $strOuterEnumInteger = 'outerEnumInteger';
    public string $strOuterEnumDefaultValue = 'outerEnumDefaultValue';
    public string $strOuterEnumIntegerDefaultValue = 'outerEnumIntegerDefaultValue';
}

