<?php
/**
 * EnumTestModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * EnumTestModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnumTestModelAttributes
{
    public string $strEnumString = 'enum_string';
    public string $strEnumStringRequired = 'enum_string_required';
    public string $strEnumInteger = 'enum_integer';
    public string $strEnumNumber = 'enum_number';
    public string $strOuterEnum = 'outer_enum';
    public string $strOuterEnumInteger = 'outer_enum_integer';
    public string $strOuterEnumDefaultValue = 'outer_enum_default_value';
    public string $strOuterEnumIntegerDefaultValue = 'outer_enum_integer_default_value';
}

