<?php
/**
 * FormatTestModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * FormatTestModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormatTestModelAttributes
{
    public string $strInteger = 'integer';
    public string $strInt32 = 'int32';
    public string $strInt64 = 'int64';
    public string $strNumber = 'number';
    public string $strFloat = 'float';
    public string $strDouble = 'double';
    public string $strDecimal = 'decimal';
    public string $strString = 'string';
    public string $strByte = 'byte';
    public string $strBinary = 'binary';
    public string $strDate = 'date';
    public string $strDateTime = 'date_time';
    public string $strUuid = 'uuid';
    public string $strPassword = 'password';
    public string $strPatternWithDigits = 'pattern_with_digits';
    public string $strPatternWithDigitsAndDelimiter = 'pattern_with_digits_and_delimiter';
}

