<?php
/**
 * NullableClassFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * NullableClassFields Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NullableClassFields
{
    public string $strIntegerProp = 'integer_prop';
    public string $strNumberProp = 'number_prop';
    public string $strBooleanProp = 'boolean_prop';
    public string $strStringProp = 'string_prop';
    public string $strDateProp = 'date_prop';
    public string $strDatetimeProp = 'datetime_prop';
    public string $strArrayNullableProp = 'array_nullable_prop';
    public string $strArrayAndItemsNullableProp = 'array_and_items_nullable_prop';
    public string $strArrayItemsNullable = 'array_items_nullable';
    public string $strObjectNullableProp = 'object_nullable_prop';
    public string $strObjectAndItemsNullableProp = 'object_and_items_nullable_prop';
    public string $strObjectItemsNullable = 'object_items_nullable';
}

